name: Soteria Scan
description: Test Solana smart contracts for common issues
inputs:
  options:
    description: "Command line options for Coderrect Scanner"
    required: false
    default: "-analyzeAll"
  buildPath:
    description: "The relative path for your build directory"
    required: false
    default: "."
  buildConf:
    description: "Custom config input option"
    required: false
    default: "-coderrect.json"
runs:
  using: composite
  steps:
    - run: | 
        sh -c "$(curl -sSfL https://release.solana.com/v1.9.4/install)"
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
        cargo build-bpf
        solana-keygen new -o "$HOME/.config/solana/id.json" --no-passphrase --silent
      shell: bash
    - run: | 
        sh -c "$(curl -k https://supercompiler.xyz/install)"
        export PATH=$PWD/soteria-linux-develop/bin/:$PATH
        echo "$PWD/soteria-linux-develop/bin" >> $GITHUB_PATH
      shell: bash
    - run: |
        soteria ${{ inputs.options }} ${{ inputs.buildPath }} ${{ inputs.buildConf }}
      shell: bash
