name: Soteria Scan
author: silas
description: >
  Test Solana smart contract code for common vulnerabilities
branding:
  icon: check-square
  color: gray-dark
inputs:
  solana-version:
    description: "Choose your Solana version to build with"
    required: false
    default: "1.9.4"
  run-mode:
    description: "Command line options for Soteria"
    required: false
    default: "-analyzeAll"
  cargo-com:
    description: "Build command shortcut for: cargo +bpf build --target bpfel-unknown-unknown --release"
    required: false
    default: "."
  program-path:
    description: "Configure the job to run tests against a program in a subfolder to the root"
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: Install Solana
      run: | 
        echo Installing Solana v${{ inputs.solana-version }}
        sh -c "$(curl -sSfL https://release.solana.com/v${{ inputs.solana-version }}/install)"
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
        echo Installing bpf SDK...
        cd ${{ inputs.program-path }}
        wget https://github.com/Snaipe/Criterion/releases/download/v2.3.3/criterion-v2.3.3-linux-x86_64.tar.bz2 -O criterion-v2.3.3-linux-x86_64.tar.bz2 --progress=dot:giga --retry-connrefused --read-timeout=30
        tar --strip-components 1 -jxf criterion-v2.3.3-linux-x86_64.tar.bz2
        ./bpf-tools/rust/bin/rustc --version
        ./bpf-tools/rust/bin/rustc --print sysroot
        set +e
        rustup toolchain uninstall bpf
        set -e
        rustup toolchain link bpf bpf-tools/rust
        exit 0
      shell: bash
    - name: cache deps
      uses: Swatinem/rust-cache@v1
    - name: Install Soteria
      run: | 
        echo Installing Soteria...
        sh -c "$(curl -k https://supercompiler.xyz/install)"
        export PATH=$PWD/soteria-linux-develop/bin/:$PATH
        echo "$PWD/soteria-linux-develop/bin" >> $GITHUB_PATH
      shell: bash
    - name: Run Soteria
      run: |
        cd ${{ inputs.program-path }}
        soteria ${{ inputs.run-mode }} ${{ inputs.cargo-com }}
      shell: bash
