name: Soteria Scan
description: >
  Test Solana smart contracts for common issues
branding:
  icon: check
  color: green

env:
  SOLANA_VERSION: "1.9.1"

inputs:
  buildPath:
    description: "The relative path for your build directory"
    required: false
    default: "."
  options:
    description: "Command line options for Coderrect Scanner"
    required: false
    default: "-analyzeAll"
    
runs:
  using: composite
  steps:
      - run: | 
        sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_VERSION }}/install)"
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
        cargo build-bpf
          solana-keygen new -o "$HOME/.config/solana/id.json" --no-passphrase --silent
      shell: bash
      
    - run: | 
        sh -c "$(curl -k https://supercompiler.xyz/install)"
        export PATH=$PWD/soteria-linux-develop/bin/:$PATH
        echo "$PWD/soteria-linux-develop/bin" >> $GITHUB_PATH
      shell: bash
    - run: |
        cd ${{ inputs.buildPath }}
        soteria ${{ inputs.options }} ${{ inputs.buildCommand }}
      shell: bash
