name: Soteria Scan
author: Silas
description: >
  Test Solana smart contract code for common vulnerabilities
branding:
  icon: check-square
  color: gray-dark
inputs:
  solanaVersion:
    description: "Choose your Solana version to build with"
    required: false
    default: "1.9.4"
  runMode:
    description: "Command line options for Soteria"
    required: false
    default: "-analyzeAll"
  cargoCom:
    description: "Build command shortcut for: cargo +bpf build --target bpfel-unknown-unknown --release"
    required: false
    default: "."
  neverFail:
    description: "Configure the job to pass even if potential vulnerabilities are discovered"
    required: false
    default: false

runs:
  using: composite
  steps:
    - run: | 
        echo Installing Solana v${{ inputs.solanaVersion }}
        sh -c "$(curl -sSfL https://release.solana.com/v${{ inputs.solanaVersion }}/install)"
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
        echo Installing bpf SDK...
        cargo build-bpf
        solana-keygen new -o "$HOME/.config/solana/id.json" --no-passphrase --silent
      shell: bash
    - run: | 
        echo Installing Soteria...
        sh -c "$(curl -k https://supercompiler.xyz/install)"
        export PATH=$PWD/soteria-linux-develop/bin/:$PATH
        echo "$PWD/soteria-linux-develop/bin" >> $GITHUB_PATH
      shell: bash
    - run: |
        soteria ${{ inputs.runMode }} ${{ inputs.cargoCom }}
      shell: bash
    - run: echo The job passed as it was set to never fail!
      run: exit 0
      if: ${{ inputs.neverFail == true}}     
    - run: |
        if grep -q "No vulnerabilities detected"; then
          echo The job passed as no vulnerabilities were found!
          exit 0
        else
          echo The job failed as potential vulnerabilities were found!
          exit 1
        fi
      shell: bash
      if: ${{ inputs.neverFail == false}}
